default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: utf8
  database: analytics_development
  pool: 5
  username: jason_ball
  password:

test:
  <<: *default
  database: analytics_test

